DROP TABLE IF EXISTS USERS CASCADE;

CREATE TABLE USERS (
USER_ID INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
USERNAME VARCHAR(100) NOT NULL,
PASS VARCHAR (100) NOT NULL,
EMAIL VARCHAR (100) NOT NULL )
ENGINE= InnoDB; 
